### ISSUE TITLE
🐛 [BUG] - Profile error

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/dashboard#31]
### Description

When a ClusterProfile/Profile is matching a cluster and there is an error, display the error message on multiple lines (it appears there is enough space for three lines).

Or at least display full message when mouse is over the error.

![Screenshot 2024-10-03 at 17 16 52](https://github.com/user-attachments/assets/ffc49768-5b57-4f3b-8b44-13d7ce07886f)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Safouene1** [comment]
Should be fixed now by #38 
- shows tooltip with full error 
-  Copy button for the error message 
- Error can be displayed on multiple lines .
